<a href="https://colab.research.google.com/github/kacperr22/data-sciance-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PODSTAWY


In [ ]:
import numpy as np
np.__version__


'1.23.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
print(x)
type(x)

[1 3]


numpy.ndarray

In [ ]:
x.ndim ## wymiar

1

In [ ]:
x.shape ## kształt

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x = np.array([1.23,1.45, 1.4])
print(x)

[1.23 1.45 1.4 ]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x = np.array([[1,2], [2.4, 5]])
print(x)

[[1.  2. ]
 [2.4 5. ]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
import numpy as np
x = np.array([[1,2,3], [4,5,7], [8,4,3]])
print(x)

[[1 2 3]
 [4 5 7]
 [8 4 3]]


In [ ]:
x.ndim

2

In [ ]:
x = np.array([[[2,3,4],
              [2,5,6]],
              [[2,3,4],
               [2,5,7]],
              [[2,3,4],
               [2,5,7]]])
print(x)

[[[2 3 4]
  [2 5 6]]

 [[2 3 4]
  [2 5 7]]

 [[2 3 4]
  [2 5 7]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 3)

In [ ]:
type(x)

numpy.ndarray

TYPY DANYCH

In [ ]:
A = np.array([2,3,4], dtype='float')
print(A)

[2. 3. 4.]


In [ ]:
B = np.array([1, 0, 1,0], dtype='bool')
print(B)

[ True False  True False]


In [ ]:
C = np.array([2.4,2.7,3.6], dtype='int')
print(C)

[2 2 3]


TWORZENIE TABLIC Numpy ndarray

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype='bool')

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(4,5), fill_value=4.2, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(start=5, stop=12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(start=1, stop=12, step=2)

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.arange(start=66, stop=12, step=-6)

array([66, 60, 54, 48, 42, 36, 30, 24, 18])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(20)


In [ ]:
A.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.reshape(5, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

PODSTAWOWE OPERACJE NA TABLICACH

In [ ]:
A = np.array([1, 4, 6, 8])
B = np.array([6, 8, 9, 1])
print(A)
print(B)

[1 4 6 8]
[6 8 9 1]


In [ ]:
print(A + B)
print(A - B)
print(A * B)
print(A / B)

[ 7 12 15  9]
[-5 -4 -3  7]
[ 6 32 54  8]
[0.16666667 0.5        0.66666667 8.        ]


In [ ]:
print(A + 3)

[ 4  7  9 11]


In [ ]:
print(B -3*A)

[  3  -4  -9 -23]


In [ ]:
print(np.add(A, B))
print(np.subtract(B, A))

[ 7 12 15  9]
[ 5  4  3 -7]


In [ ]:
print(np.multiply(A, B))
print(np.divide(A, B))

[ 6 32 54  8]
[0.16666667 0.5        0.66666667 8.        ]


In [ ]:
X = np.array([[2,3], [4,5]])
Y = np.array([[6,2], [-1, 0]])
print(X)
print(Y)

[[2 3]
 [4 5]]
[[ 6  2]
 [-1  0]]


In [ ]:
np.dot(X, Y)

array([[ 9,  4],
       [19,  8]])

In [ ]:
print(X * Y)

[[12  6]
 [-4  0]]


In [ ]:
Y.dot(X)

array([[20, 28],
       [-2, -3]])

In [ ]:
Y.dot(Y)

array([[34, 12],
       [-6, -2]])

In [ ]:
X @ Y

array([[ 9,  4],
       [19,  8]])

In [ ]:
X.dot(Y)

array([[ 9,  4],
       [19,  8]])

LICZBY PSEUDOLOSOWE

In [2]:
import numpy as np

In [26]:
np.random.randn()

0.8590352922883386

In [11]:
np.random.randn(10)

array([ 1.73736306,  0.5086061 , -0.60417876, -0.77205221, -0.74318508,
       -0.13369588,  1.10912666, -0.42261858, -0.43684163,  0.40091799])

In [19]:
np.random.rand()

0.35290083767237723

In [28]:
np.random.rand(5,3)

array([[0.62824158, 0.97945514, 0.32855109],
       [0.12504082, 0.90361905, 0.822375  ],
       [0.90913505, 0.55859581, 0.77992783],
       [0.83057932, 0.64338819, 0.74558882],
       [0.82961736, 0.23160411, 0.19020874]])

In [31]:
np.random.randint(20) ## od 0 do 19

11

In [32]:
np.random.randint(low=5, high=55, size=5)

array([40, 33, 38, 50, 12])

In [37]:
np.random.randint(2, 20, 10)

array([ 3, 11,  7,  4, 16, 10, 17, 19, 12,  9])

In [64]:
x = np.array([2, 5, 7, 4, 5, 6, 11, 737, 22, 2, 'dupa', 'jajko'])
print(x)

['2' '5' '7' '4' '5' '6' '11' '737' '22' '2' 'dupa' 'jajko']


In [52]:
np.random.choice(x, 3)

array([5, 5, 2])

In [68]:
np.random.shuffle(x)

In [69]:
print(x)

['6' '5' '2' '2' '22' '5' 'jajko' '7' '4' '737' 'dupa' '11']


PODSTAWOWE FUNKCJE

In [72]:
np.exp(4) ## liczba eulera

54.598150033144236

In [ ]:
help(np.exp)

In [75]:
np.sqrt(88)

9.38083151964686

In [77]:
np.abs(-5)

5

In [78]:
np.any([2, 5, 0,1])

True

In [80]:
np.any([False, 0, 1 ])

True

In [81]:
np.any([False, 0, ])

False

In [ ]:
np.any([False, 0, 'dupa' ]) ## nie zadziała

In [85]:
np.all([2, 4 , 5, 0])

False

In [86]:
np.all([2, 4 , 5, 1])

True

In [92]:
np.bool(0)

<ipython-input-92-e41969e36f0a>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool(0)


False

In [94]:
A = np.random.rand(10)
print(A)

[0.41869999 0.70874172 0.85520013 0.80067903 0.94813916 0.07224389
 0.01633626 0.65042119 0.05775352 0.97762891]


In [96]:
np.argmin(A) ## zwróci nam indeks elementu z najmniejsza wartości

6

In [97]:
np.argmax(A) ## zwróci nam indeks elementu z największa wartości

9

In [106]:
np.argsort(A) ## posortowane rosnąco indeksy

array([6, 8, 5, 0, 7, 1, 3, 2, 4, 9])

In [99]:
np.min(A) ## zwróci najmniejszą wartośc

0.016336262789386047

In [100]:
np.max(A) ## zwróci największa wartośc

0.977628908421476

In [102]:
np.min(np.random.randn(2,4))

-1.23530770778088

In [103]:
np.random.randn(2,4)

array([[ 1.0901058 , -0.43828868, -1.39465435,  1.05818327],
       [-0.69048582, -0.63423695,  0.40784833,  0.61285292]])

In [104]:
np.sort(A)

array([0.01633626, 0.05775352, 0.07224389, 0.41869999, 0.65042119,
       0.70874172, 0.80067903, 0.85520013, 0.94813916, 0.97762891])

In [110]:
np.mean(A) ## średnia arytmetyczna

0.5505843813533607

In [111]:
np.median(A) ## mediana

0.6795814582902204

In [112]:
np.std(A) ## odchylenie standardowe

0.36128139813983356

INDEKSOWANIE I WYCINANIE TABLIC

In [114]:
x = np.arange(30)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [115]:
## A[idx], A[start:stop], A[start:], A[:stop]

In [123]:
print(x[2])
print(x[2:4])
print(x[5:])
print(x[:11])

2
[2 3]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [127]:
y = x.reshape(5,6)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [129]:
y[2,1]

13

In [131]:
y[0]

array([0, 1, 2, 3, 4, 5])

In [135]:
y[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [137]:
y[3,2] = 21 ## zmiana elementu w tablicy

In [138]:
y


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 21, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

ITERACJE PO TABLICACH

In [156]:
A = np.arange(start=-10, stop=10, step=1/2)

In [157]:
print(A)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


In [173]:
B = A.reshape(5, 8)

In [174]:
for row in B:
  print(row)

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5]
[-6.  -5.5 -5.  -4.5 -4.  -3.5 -3.  -2.5]
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5]
[6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [176]:
for row in B:
  print(row[2])

-9.0
-5.0
-1.0
3.0
7.0


In [177]:
for row in B:
  print(row[2:4])

[-9.  -8.5]
[-5.  -4.5]
[-1.  -0.5]
[3.  3.5]
[7.  7.5]


In [ ]:
for item in B.flat: ## zamienia tablice 2 wymiarową w liste
  print(item)

In [181]:
B.ravel()

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [183]:
for item in B:
  print(item/3)

[-3.33333333 -3.16666667 -3.         -2.83333333 -2.66666667 -2.5
 -2.33333333 -2.16666667]
[-2.         -1.83333333 -1.66666667 -1.5        -1.33333333 -1.16666667
 -1.         -0.83333333]
[-0.66666667 -0.5        -0.33333333 -0.16666667  0.          0.16666667
  0.33333333  0.5       ]
[0.66666667 0.83333333 1.         1.16666667 1.33333333 1.5
 1.66666667 1.83333333]
[2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667]


MASKI LOGICZNE


In [185]:
x = np.arange(start=-5, stop=15, step=1/2)
print(x)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


In [186]:
y = x.reshape(10, -1)

array([[-5. , -4.5, -4. , -3.5],
       [-3. , -2.5, -2. , -1.5],
       [-1. , -0.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5],
       [13. , 13.5, 14. , 14.5]])

In [188]:
y > 0

array([[False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [191]:
y[y > 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [192]:
y.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 21, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [194]:
np.bitwise_and(y>0, y<8)

array([[False,  True,  True,  True,  True,  True],
       [ True,  True, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [197]:
np.bitwise_or(y>0, y>2)

array([[False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [200]:
C = np.arange(start=-4, stop=8, step=1/4)

In [202]:
C.reshape(4, -1)

array([[-4.  , -3.75, -3.5 , -3.25, -3.  , -2.75, -2.5 , -2.25, -2.  ,
        -1.75, -1.5 , -1.25],
       [-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,
         1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,
         4.25,  4.5 ,  4.75],
       [ 5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,
         7.25,  7.5 ,  7.75]])

In [ ]:
C