<a href="https://colab.research.google.com/github/kacperr22/data-sciance-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.23.5'

### <a name='a1'></a> Norma wektora, długość wektora w $R^{2}$

${\mathbf  {v}} = [v_{1}, v_{2}]$   
$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}}}$

In [3]:
v1 = np.array([7, 4])
v1

array([7, 4])

In [4]:
np.linalg.norm(v1)

8.06225774829855

### <a name='a2'></a> Norma euklidesowa w $R^{n}$

$\left\|{\mathbf  {v}}\right\|={\sqrt  {v_{1}^{2}+v_{2}^{2}+\cdots +v_{n}^{2}}}$

In [2]:
v2 = np.array([-8, 12, 24])
np.linalg.norm(v2)

28.0

### <a name='a3'></a> Odległóść dwóch punktów na płaszczyźnie


In [5]:
p = np.array([3, 5])
q = np.array([0, 2])

np.linalg.norm(p - q)

4.242640687119285

### <a name='a4'></a> Odległóść dwóch punktów w przestrzeni $R^{n}$


 \begin{aligned}d(\mathbf {p} ,\mathbf {q} )=d(\mathbf {q} ,\mathbf {p} )&={\sqrt {(q_{1}-p_{1})^{2}+(q_{2}-p_{2})^{2}+\cdots +(q_{n}-p_{n})^{2}}}\\[8pt]&={\sqrt {\sum _{i=1}^{n}(q_{i}-p_{i})^{2}}}\end{aligned}



In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

### <a name='a5'></a> Mnożenie macierzy



$${A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1n}\\a_{21}&a_{22}&\cdots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mn}\\\end{bmatrix}}$$
A - macierz wymairu $m\ x\ n$

$$ {B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1p}\\b_{21}&b_{22}&\cdots &b_{2p}\\\vdots &\vdots &\ddots &\vdots \\b_{n1}&b_{n2}&\cdots &b_{np}\\\end{bmatrix}}$$
B - macierz wymairu $n\ x\ p$

$$C = AB$$
C - macierz wymiaru $m\ x\ p$  
Aby móc pomnożyć dwie macierze liczba liczba kolumn w lewej macierzy musi zgadzać się z liczbą wierszy prawej macierzy.

Mnożenie macierzy nie jest przemienne! Tzn. $$AB \neq BA$$




### Przykład 1
$ X = \begin{bmatrix}5&3\\3&9\end{bmatrix}$, $ Y= \begin{bmatrix}1\\-1\end{bmatrix} $  
$X$ macierz 2x2  
$Y$ macierz 2x1
$$Z = X \cdot Y = \begin{bmatrix}5&3\\3&9\end{bmatrix} \cdot \begin{bmatrix}1\\-1\end{bmatrix} = \begin{bmatrix}2\\-6\end{bmatrix}$$
$Z$ macierz 2x1


In [18]:
X = np.array([[5,3], [3,9]])
Y = np.array([[1],[-1]])
print('X:', X, '\n')
print('Y:', Y)

X: [[5 3]
 [3 9]] 

Y: [[ 1]
 [-1]]


In [19]:
Z = np.dot(X, Y) ## mnożenie macierzy

In [20]:
print(Z)

[[ 2]
 [-6]]


In [21]:
Z.shape

(2, 1)

### Przykład 2
$X = \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix}$, $Y = \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix}$

$X$ macierz 2x3  
$Y$ macierz 3x3
$$Z = X \cdot Y =  \begin{bmatrix}2&-1&3\\3&1&0\end{bmatrix} \cdot \begin{bmatrix}2&1&-1\\0&-1&2\\3&2&0\end{bmatrix} = \begin{bmatrix}13&9&-4\\6&2&-1\end{bmatrix}$$
$Z$ macierz 2x3

In [23]:
X = np.array([[3,4,-1], [5, 0, 2]])
Y = np.array([[4,5,2], [4,9,-2], [1, -1, 2]])
print(X, '\n')
print(Y)


[[ 3  4 -1]
 [ 5  0  2]] 

[[ 4  5  2]
 [ 4  9 -2]
 [ 1 -1  2]]


In [24]:
print(np.dot(X, Y)) ## macierzy wynikowa będzie 2x3 liczby wierszy z 1 macierzy na liczbe kolumn z drugiej macierzy

[[27 52 -4]
 [22 23 14]]


### <a name='a6'></a> Wyznacznik macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

#### Oznaczenia:

${\displaystyle |A|=\left|{\begin{array}{c}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{array}}\right|} $  lub  $ {\displaystyle \det A=\det {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$

#### Przykład:
${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}}=a_{11}a_{22}-a_{12}a_{21}}$

${\displaystyle \det A={\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}}=a_{11}a_{22}a_{33}+a_{21}a_{32}a_{13}+a_{31}a_{12}a_{23}-a_{21}a_{12}a_{33}-a_{11}a_{32}a_{23}-a_{31}a_{22}a_{13}}$

${\displaystyle \det A={\begin{vmatrix}2&4\\-1&3\end{vmatrix}}=2\cdot3-4\cdot(-1)} = 6 + 4 = 10 $


In [27]:
A = np.array([[2,4], [-1,3]])
np.linalg.det(A)

9.999999999999998

In [28]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

### <a name='a7'></a> Ślad macierzy

$${\displaystyle A={\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{n1}&a_{n2}&\dots &a_{nn}\end{bmatrix}}}$$
$A$ - macierz wymiaru nxn

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{n}a_{ii}=a_{11}+a_{22}+\dots +a_{nn}}$

#### Przykład:
$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

${\displaystyle \operatorname {tr} (A)=\sum _{i=1}^{2}a_{ii}=a_{11}+a_{22} = 2 + 3 = 5}$

In [29]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

###  <a name='a8'></a>  Macierz jednostkowa

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Przykłady
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

In [30]:
np.eye(5, dtype='float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### <a name='a9'></a>  Macierz odwrotna

$A$ - macierz kwadratowa stopnia $n$. Macierz $A$ posiada macierz odwrotną, gdy istnieje macierz $B$, taka, że
$$AB = BA = I$$

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$

In [32]:
A
B = np.linalg.inv(A)

In [33]:
print(B)

[[ 0.3 -0.4]
 [ 0.1  0.2]]


In [41]:
np.dot(A, B)


array([[1., 0.],
       [0., 1.]])

In [42]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.set_printoptions(precision=4, suppress=True)
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

### <a name='a10'></a> Macierz transponowana

Zamiana wierszy na kolumny i kolumny na wiersze.

#### Przykład 1:

$A = \begin{bmatrix}2&4\\-1&3\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&-1\\4&3\end{bmatrix}$

#### Przykład 2:
$A = \begin{bmatrix}2&1&-1\\0&-1&2\end{bmatrix}$,
$A^{T} = \begin{bmatrix}2&0\\1&-1\\-1&2\end{bmatrix}$

In [44]:
A = np.array([[2, 4], [-1,3]])
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [45]:
A.T

array([[ 2, -1],
       [ 4,  3]])

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  






In [48]:
A = np.array([[2,4], [1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [50]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [53]:
C = np.dot(np.linalg.inv(A), B)
print(C)

[[1.]
 [2.]]


In [54]:
C.shape

(2, 1)

FUNKCJE STATYSTCZNE

In [58]:
price = np.arange(start=10, stop=19, step=0.33)
print(price)

[10.   10.33 10.66 10.99 11.32 11.65 11.98 12.31 12.64 12.97 13.3  13.63
 13.96 14.29 14.62 14.95 15.28 15.61 15.94 16.27 16.6  16.93 17.26 17.59
 17.92 18.25 18.58 18.91]


In [74]:
price_reshape = price.reshape(7, -1)

In [75]:
np.random.shuffle(price_reshape)
print(price_reshape)

[[10.99 12.64 15.61 14.62]
 [16.93 18.58 10.66 13.63]
 [18.91 12.97 13.96 17.92]
 [17.26 11.65 10.33 18.25]
 [15.28 11.32 16.27 14.95]
 [12.31 13.3  10.   15.94]
 [11.98 14.29 17.59 16.6 ]]


In [83]:
price2 = np.random.rand(5, 4)
print(price2)

[[0.4586 0.6115 0.8714 0.4498]
 [0.3968 0.0523 0.218  0.0018]
 [0.2991 0.9539 0.8282 0.0666]
 [0.4007 0.0488 0.0757 0.614 ]
 [0.8731 0.8853 0.4947 0.5671]]


In [84]:
price2.sum(axis=0) ## dodawanie po kolumnach

array([2.4283, 2.5519, 2.488 , 1.6992])

In [85]:
price2.sum(axis=1) ## dodawanie po wierszach

array([2.3913, 0.6689, 2.1478, 1.1392, 2.8201])

In [86]:
np.sum(price2) ## dodawanie wszystkich elementów macierzy

9.167388742515588

In [90]:
round(np.min(price2), 5)

0.00181

In [97]:
np.max(price2, axis=1)

array([0.8714, 0.3968, 0.9539, 0.614 , 0.8853])

In [99]:
np.median(price2) ## miediana

0.4541966919787473

In [100]:
np.mean(price2, axis=0) ## wartość srednia po kolumnach

array([0.4857, 0.5104, 0.4976, 0.3398])

In [102]:
np.std(price2, axis=0) ## odhcylenie po kolumnach

array([0.2004, 0.3925, 0.3179, 0.2561])

In [104]:
np.var(price2, axis=1) ## wariacja po wierszach

array([0.0291, 0.024 , 0.1341, 0.0553, 0.031 ])